// flow-typed signature: b67f723b53306cfacbd207d108a9a1f1
// flow-typed version: <<STUB>>/auto-launch_v^5.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auto-launch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'auto-launch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auto-launch/dist/AutoLaunchLinux' {
  declare module.exports: any;
}

declare module 'auto-launch/dist/AutoLaunchMac' {
  declare module.exports: any;
}

declare module 'auto-launch/dist/AutoLaunchWindows' {
  declare module.exports: any;
}

declare module 'auto-launch/dist/fileBasedUtilities' {
  declare module.exports: any;
}

declare module 'auto-launch/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auto-launch/dist/AutoLaunchLinux.js' {
  declare module.exports: $Exports<'auto-launch/dist/AutoLaunchLinux'>;
}
declare module 'auto-launch/dist/AutoLaunchMac.js' {
  declare module.exports: $Exports<'auto-launch/dist/AutoLaunchMac'>;
}
declare module 'auto-launch/dist/AutoLaunchWindows.js' {
  declare module.exports: $Exports<'auto-launch/dist/AutoLaunchWindows'>;
}
declare module 'auto-launch/dist/fileBasedUtilities.js' {
  declare module.exports: $Exports<'auto-launch/dist/fileBasedUtilities'>;
}
declare module 'auto-launch/dist/index.js' {
  declare module.exports: $Exports<'auto-launch/dist/index'>;
}
