// flow-typed signature: ad572f07343364afcfe8365ed3413db3
// flow-typed version: <<STUB>>/denon_remote_vgithub:figedi/denon_remote/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'denon_remote'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'denon_remote' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'denon_remote/bin/index' {
  declare module.exports: any;
}

declare module 'denon_remote/lib/client' {
  declare module.exports: any;
}

declare module 'denon_remote/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'denon_remote/bin/index.js' {
  declare module.exports: $Exports<'denon_remote/bin/index'>;
}
declare module 'denon_remote/lib/client.js' {
  declare module.exports: $Exports<'denon_remote/lib/client'>;
}
declare module 'denon_remote/lib/index.js' {
  declare module.exports: $Exports<'denon_remote/lib/index'>;
}
