// flow-typed signature: 31c0e2d0c759aa7edb62d0d749185e34
// flow-typed version: <<STUB>>/photon_vgithub:connors/photon/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'photon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'photon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'photon/dist/template-app/app' {
  declare module.exports: any;
}

declare module 'photon/dist/template-app/js/menu' {
  declare module.exports: any;
}

declare module 'photon/docs/assets/js/docs' {
  declare module.exports: any;
}

declare module 'photon/docs/assets/js/jq' {
  declare module.exports: any;
}

declare module 'photon/docs/assets/js/sticky' {
  declare module.exports: any;
}

declare module 'photon/docs/dist/template-app/app' {
  declare module.exports: any;
}

declare module 'photon/docs/dist/template-app/js/index' {
  declare module.exports: any;
}

declare module 'photon/docs/dist/template-app/js/menu' {
  declare module.exports: any;
}

declare module 'photon/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'photon/dist/template-app/app.js' {
  declare module.exports: $Exports<'photon/dist/template-app/app'>;
}
declare module 'photon/dist/template-app/js/menu.js' {
  declare module.exports: $Exports<'photon/dist/template-app/js/menu'>;
}
declare module 'photon/docs/assets/js/docs.js' {
  declare module.exports: $Exports<'photon/docs/assets/js/docs'>;
}
declare module 'photon/docs/assets/js/jq.js' {
  declare module.exports: $Exports<'photon/docs/assets/js/jq'>;
}
declare module 'photon/docs/assets/js/sticky.js' {
  declare module.exports: $Exports<'photon/docs/assets/js/sticky'>;
}
declare module 'photon/docs/dist/template-app/app.js' {
  declare module.exports: $Exports<'photon/docs/dist/template-app/app'>;
}
declare module 'photon/docs/dist/template-app/js/index.js' {
  declare module.exports: $Exports<'photon/docs/dist/template-app/js/index'>;
}
declare module 'photon/docs/dist/template-app/js/menu.js' {
  declare module.exports: $Exports<'photon/docs/dist/template-app/js/menu'>;
}
declare module 'photon/Gruntfile.js' {
  declare module.exports: $Exports<'photon/Gruntfile'>;
}
