// flow-typed signature: e957a9da6018130feff155484b0f5448
// flow-typed version: <<STUB>>/rc-slider_v^5.4.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-slider/dist/rc-slider' {
  declare module.exports: any;
}

declare module 'rc-slider/dist/rc-slider.min' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/Handle' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/index' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/Marks' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/Slider' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/Steps' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/Track' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-slider/dist/rc-slider.js' {
  declare module.exports: $Exports<'rc-slider/dist/rc-slider'>;
}
declare module 'rc-slider/dist/rc-slider.min.js' {
  declare module.exports: $Exports<'rc-slider/dist/rc-slider.min'>;
}
declare module 'rc-slider/lib/Handle.js' {
  declare module.exports: $Exports<'rc-slider/lib/Handle'>;
}
declare module 'rc-slider/lib/index.js' {
  declare module.exports: $Exports<'rc-slider/lib/index'>;
}
declare module 'rc-slider/lib/Marks.js' {
  declare module.exports: $Exports<'rc-slider/lib/Marks'>;
}
declare module 'rc-slider/lib/Slider.js' {
  declare module.exports: $Exports<'rc-slider/lib/Slider'>;
}
declare module 'rc-slider/lib/Steps.js' {
  declare module.exports: $Exports<'rc-slider/lib/Steps'>;
}
declare module 'rc-slider/lib/Track.js' {
  declare module.exports: $Exports<'rc-slider/lib/Track'>;
}
