// flow-typed signature: aa86d57a5cb580eb50ddce957e193c6e
// flow-typed version: <<STUB>>/react-photonkit_v^0.4.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-photonkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-photonkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-photonkit/dist/photon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-photonkit/dist/photon.js' {
  declare module.exports: $Exports<'react-photonkit/dist/photon'>;
}
